مقایسه تعداد ماه های سال
SultanimMubin/Path pull request #10
Opened 2021-08-14 13:56 UTC by walaa38

some changes

2021-08-14 17:19 UTC, nemati768 reviewed
thanks walla

2021-08-14 19:08 UTC, Nefcanto requested changes
@walaa38 please return the title back to it's original form.

we want titles, in this phase.

the shorter the better.

2021-08-14 19:37 UTC, walaa38 commented
i have changed

2021-08-16 18:12 UTC, walaa38 commented
pains

2021-08-16 18:14 UTC, merged