changes of Motor neurons
SultanimMubin/Path pull request #14
Opened 2021-08-20 18:13 UTC by Adelll21

2021-08-20 18:23 UTC, Nefcanto requested changes
Hi Adel, great work. The content is good. Simplification is really good. However, you're still using HTML. Please use Markdown. In case you have problems, let me know or I can connect to you to guide you. Fix that and this request would be pulled.

Thanks.

2021-08-20 18:47 UTC, Adelll21 commented
> Hi Adel, great work. The content is good. Simplification is really good. However, you're still using HTML. Please use Markdown. In case you have problems, let me know or I can connect to you to guide you. Fix that and this request would be pulled.
> 
> Thanks.

Hi Saeid, Thanks For your helpful guide. But I should say that I use Markdown and I didn't use HTML, please tell me more about that. Also About my little problem, I understood that how can I use dash, hashtag and another tools. Therefore, I didn't know that what was you meant about "Fix that". please clear that phrase.

2021-08-20 19:05 UTC, Nefcanto commented
@Adelll21 

This is the [link of the file in your repository](https://github.com/Adelll21/Path/blob/master/contents/path/design/motor-neuron.md). Please go to the edit mode. What you see there is not markdown. It's HTML. Let me know if you need help in changing it into markdown.

2021-08-20 21:48 UTC, Adelll21 commented
> @Adelll21
> 
> This is the [link of the file in your repository](https://github.com/Adelll21/Path/blob/master/contents/path/design/motor-neuron.md). Please go to the edit mode. What you see there is not markdown. It's HTML. Let me know if you need help in changing it into markdown.

I see. This is the link that I used for changing the text, [https://www.tablesgenerator.com/markdown_tables]. I haven't understood what was you meant about using HTML or Markdown. I definitely need your help, Please help me to do it right.

Thanks for your time.

2021-08-21 07:56 UTC, Adelll21 commented
Hi Saeid, I've done the changes. please check.

2021-08-21 10:43 UTC, Nefcanto requested changes
Thank you so much for this work.

However, you're overusing tables. 

Those are simple lists. Tables are for when we need to have more than one column.

Please replace tables with simple lists.

Thank you.

2021-08-21 10:54 UTC, Nefcanto requested changes
Thank you Adel. 

This is the spirit we need for teamwork. 

However, to keep stuff simple, let's fix one file at a time.

2021-08-21 10:54 UTC, Nefcanto commented on contents/path/design/blood-and-car-fluids.md
> +#### Point: These Fluids Are Seperate
I guess it's better to say:

Separate fluids, separate pumping, separate piping

2021-08-21 10:54 UTC, Nefcanto commented on contents/path/design/blood-and-car-fluids.md
> +<hr />
To place a line in markdown, simply use three stars:

***

please don't use HTML. `<br />` is HTML tag.

2021-08-21 10:54 UTC, Nefcanto commented on contents/path/design/cns-pns-government.md
> +| Handling and Fixing Defects | Handling and Fixing Fefects |
misspelling here. I recommend that you install "Grammarly" for chrome. It's an awesome extension that checks for misspellings.

Also, CNS + PNS

Also, we might change those items in the future. But for now, they are good.

2021-08-21 10:54 UTC, Nefcanto commented on contents/path/design/coaxial-cable-and-esophagus.md
>  <img src="https://www.electricaltechnology.org/wp-content/uploads/2015/02/Why-Coaxial-Cables-are-Highly-Insulated.jpg" alt="Coaxial cable" />
Use markdown for images.
This is the formula:

![title](url)

2021-08-21 10:54 UTC, Nefcanto commented on contents/path/design/coaxial-cable-and-esophagus.md
> +- Cable Cross Section (For Cable)
It's nice that you have deleted the **judgemental** part. Thank you.

2021-08-21 10:54 UTC, Nefcanto commented on contents/path/design/motor-neuron.md
> +# Motor Neurons
We have a problem here. Both you and the architect worked on this file. So for this reason, I recommend that we go, one by one.

2021-08-21 13:35 UTC, Adel-Laali commented
> Thank you so much for this work.
> 
> However, you're overusing tables.
> 
> Those are simple lists. Tables are for when we need to have more than one column.
> 
> Please replace tables with simple lists.
> 
> Thank you.

Thank you for all of your useful and helpful comments.
About using too many tables, I should say that I suppose we're going to use tables instead long and judgemental sentences. Thanks for remembering. I consider that to use list for one column and use tables for more than one column.

2021-08-21 13:49 UTC, Adel-Laali commented
> Thank you Adel.
> 
> This is the spirit we need for teamwork.
> 
> However, to keep stuff simple, let's fix one file at a time.

I got that we must make phases and sentences too simple. I'll consider that.
Just tell me what will we fix?

2021-08-21 13:50 UTC, Adel-Laali commented on contents/path/design/blood-and-car-fluids.md
> +#### Point: These Fluids Are Seperate
Yes, I agree with you. I'll fix this.

2021-08-21 13:56 UTC, Adel-Laali commented on contents/path/design/blood-and-car-fluids.md
> +<hr />
I see. I don't know what do I use that it's not HTML😅. Please send me a Text including HTML words or whatever else. Please send in Instagram.

Thanks

2021-08-21 13:59 UTC, Adel-Laali commented on contents/path/design/cns-pns-government.md
> +| Handling and Fixing Defects | Handling and Fixing Fefects |
I didn't find out that what was your meant. Please make it clear.

2021-08-21 14:00 UTC, Adel-Laali commented on contents/path/design/coaxial-cable-and-esophagus.md
>  <img src="https://www.electricaltechnology.org/wp-content/uploads/2015/02/Why-Coaxial-Cables-are-Highly-Insulated.jpg" alt="Coaxial cable" />
I see.
But I don't know how do I use markdown tools. I just know a little about it.

2021-08-21 14:02 UTC, Adel-Laali commented on contents/path/design/coaxial-cable-and-esophagus.md
> +- Cable Cross Section (For Cable)
Yes. We have to explain our thoughts and than people choose which one is better. It's their choice.

2021-08-21 14:10 UTC, Adel-Laali commented on contents/path/design/motor-neuron.md
> +# Motor Neurons
I'm totally surprised!!!
I Told my part in our Instagram group. I wrote the address that I have choose.
I remember that architect chose Stop-codon or something.
However, I'll fix the parts that you have told than Tell me that it's get right or not.

Thanks for your time.

2021-08-21 16:45 UTC, Nefcanto approved these changes
awesome, thank you

2021-08-23 05:28 UTC, merged